### ISSUE TITLE
Generate Images

### ISSUE THREAD

**Issue by ExoAis** [konstantinjdobler/multi-conditional-stylegan#1]
After the training, how am I supposed to generate the images? Which file should I run? If it is Generate Conditional Mass.py then in the file it's written len(conditions) = 1 but what if we have 2 or more conditions for the image?

**Comment by konstantinjdobler** [comment]
You will want to use the `generate_grid.py` script, e.g.:

```sh
 python generate_grid.py --network_pkl /path/to/model  --outdir /path/to/outdir  --conditions "style=unknown;painter=Monet;genre=landscape;keywords=trees,ocean;emotions=contentment" --seeds 1234 --mmdc ./annotations/painter-style-genre-keywords-emotions/ --images_per_class 4
```

More options are documented in the script.

**Comment by ExoAis** [comment]
Thank You.
